// Generated by OABuilder
package com.theice.tsam.model.oa.propertypath;
 
import com.theice.tsam.model.oa.*;
 
public class PackageTypePP {
    private static ApplicationTypePPx applicationTypes;
    private static ApplicationVersionPPx applicationVersions;
    private static PackageVersionPPx packageVersions;
    private static SiloConfigVersioinPPx siloConfigVersioins;
     

    public static ApplicationTypePPx applicationTypes() {
        if (applicationTypes == null) applicationTypes = new ApplicationTypePPx(PackageType.P_ApplicationTypes);
        return applicationTypes;
    }

    public static ApplicationVersionPPx applicationVersions() {
        if (applicationVersions == null) applicationVersions = new ApplicationVersionPPx(PackageType.P_ApplicationVersions);
        return applicationVersions;
    }

    public static PackageVersionPPx packageVersions() {
        if (packageVersions == null) packageVersions = new PackageVersionPPx(PackageType.P_PackageVersions);
        return packageVersions;
    }

    public static SiloConfigVersioinPPx siloConfigVersioins() {
        if (siloConfigVersioins == null) siloConfigVersioins = new SiloConfigVersioinPPx(PackageType.P_SiloConfigVersioins);
        return siloConfigVersioins;
    }

    public static String id() {
        String s = PackageType.P_Id;
        return s;
    }

    public static String code() {
        String s = PackageType.P_Code;
        return s;
    }

    public static String packageName() {
        String s = PackageType.P_PackageName;
        return s;
    }

    public static String pomGroupId() {
        String s = PackageType.P_PomGroupId;
        return s;
    }

    public static String pomArtifactId() {
        String s = PackageType.P_PomArtifactId;
        return s;
    }
}
 
