// Generated by OABuilder
package test.theice.tsam.model.oa.propertypath;
 
import test.theice.tsam.model.oa.OperatingSystem;
import test.theice.tsam.model.oa.propertypath.OSVersionPPx;

import test.theice.tsam.model.oa.*;
 
public class OperatingSystemPP {
    private static OSVersionPPx osVersions;
     

    public static OSVersionPPx osVersions() {
        if (osVersions == null) osVersions = new OSVersionPPx(OperatingSystem.P_OSVersions);
        return osVersions;
    }

    public static String id() {
        String s = OperatingSystem.P_Id;
        return s;
    }

    public static String name() {
        String s = OperatingSystem.P_Name;
        return s;
    }

    public static String type() {
        String s = OperatingSystem.P_Type;
        return s;
    }

    public static String userId() {
        String s = OperatingSystem.P_UserId;
        return s;
    }
}
 
