// Generated by OABuilder
package com.theice.tsam.remote;
 
import com.viaoa.remote.multiplexer.annotation.OARemoteInterface;
 
@OARemoteInterface
public interface RemoteLLADInterface {
    // todo: define methods here
 
    // todo: create impl in control/remoteclient/RemoteLLADController.java
 
}
 
