// Generated by OABuilder
package com.theice.tsam.remote;

import com.theice.tsam.model.oa.*;
import com.theice.tsam.remote.RemoteMRADInterface;
import com.theice.tsam.delegate.oa.*;
import com.theice.tsam.delegate.*;
import com.theice.tsam.delegate.ModelDelegate;
import com.theice.tsam.delegate.oa.MRADServerCommandDelegate;


public class RemoteModelImpl implements RemoteModelInterface {

    public void mradServerCommand_runOnServer(MRADServerCommand mradServerCommand) throws Exception {
        mradServerCommand.runOnServer();
    }
}

