// Generated by OABuilder
package com.theice.tsam.remote;

import com.theice.tsam.model.oa.*;
import com.theice.tsam.remote.RemoteMRADInterface;
import com.theice.tsam.delegate.oa.*;
import com.theice.tsam.delegate.*;
import com.theice.tsam.delegate.ModelDelegate;
import com.theice.tsam.delegate.oa.MRADServerCommandDelegate;

import com.viaoa.remote.multiplexer.annotation.OARemoteInterface;

@OARemoteInterface
public interface RemoteModelInterface {
    public final static String BindName = "RemoteModel";

    void mradServerCommand_runOnServer(MRADServerCommand mradServerCommand) throws Exception;
}

