// Generated by OABuilder
package com.theice.tsactest2.model.oa.propertypath;
 
import com.theice.tsactest2.model.oa.*;
 
public class SiloTypePP {
    private static ApplicationTypePPx applicationTypes;
    private static SiloPPx silos;
     

    public static ApplicationTypePPx applicationTypes() {
        if (applicationTypes == null) applicationTypes = new ApplicationTypePPx(SiloType.P_ApplicationTypes);
        return applicationTypes;
    }

    public static SiloPPx silos() {
        if (silos == null) silos = new SiloPPx(SiloType.P_Silos);
        return silos;
    }

    public static String id() {
        String s = SiloType.P_Id;
        return s;
    }

    public static String name() {
        String s = SiloType.P_Name;
        return s;
    }

    public static String type() {
        String s = SiloType.P_Type;
        return s;
    }
}
 
