// Generated by OABuilder
package com.tmgsc.hifivetest.model.oa.filter;

import com.tmgsc.hifivetest.model.oa.*;
import com.viaoa.annotation.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import java.util.*;

@OAClass(useDataSource=false, localOnly=true)
@OAClassFilter(name = "MissingApprover", displayName = "Missing Approver", hasInputParams = false, description = "This approval does not know who to go to")
public class PointsApprovalMissingApproverFilter extends OAObject implements CustomHubFilter {
    private static final long serialVersionUID = 1L;


    public static final String PPCode = ":MissingApprover()";
    private Hub<PointsApproval> hubMaster;
    private Hub<PointsApproval> hub;
    private HubFilter<PointsApproval> filter;
    private boolean bAllHubs;

    public PointsApprovalMissingApproverFilter(Hub<PointsApproval> hub) {
        this(true, null, hub);
    }
    public PointsApprovalMissingApproverFilter(Hub<PointsApproval> hubMaster, Hub<PointsApproval> hub) {
        this(false, hubMaster, hub);
    }
    public PointsApprovalMissingApproverFilter(boolean bAllHubs, Hub<PointsApproval> hubMaster, Hub<PointsApproval> hubFiltered) {
        this.hubMaster = hubMaster;
        this.hub = hubFiltered;
        if (hubMaster == null) this.hubMaster = new Hub<PointsApproval>(PointsApproval.class);
        this.bAllHubs = bAllHubs;
        getHubFilter(); // create filter
    }


    public void reset() {
    }

    public boolean isDataEntered() {
        return false;
    }
    public void refresh() {
        if (filter != null) getHubFilter().refresh();
    }

    @Override
    public HubFilter<PointsApproval> getHubFilter() {
        if (filter == null) {
            filter = createHubFilter(hubMaster, hub, bAllHubs);
        }
        return filter;
    }
    protected HubFilter<PointsApproval> createHubFilter(final Hub<PointsApproval> hubMaster, Hub<PointsApproval> hub, boolean bAllHubs) {
        HubFilter<PointsApproval> filter = new HubFilter<PointsApproval>(hubMaster, hub) {
            @Override
            public boolean isUsed(PointsApproval pointsApproval) {
                return PointsApprovalMissingApproverFilter.this.isUsed(pointsApproval);
            }
        };
        filter.addDependentProperty(PointsApproval.P_Employee);
 
        if (!bAllHubs) return filter;
        // need to listen to all PointsApproval
        HubObjectCacheAdder hubCacheAdder = new HubObjectCacheAdder(hubMaster);
        return filter;
    }

    public boolean isUsed(PointsApproval pointsApproval) {
        Employee employee = pointsApproval.getEmployee();
        if (employee != null) {
            return false;
        }
        return true;
    }
    
}
