// Generated by OABuilder
package com.tmgsc.hifivetest.model.oa.filter;

import com.viaoa.annotation.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import java.util.*;
import com.tmgsc.hifivetest.model.oa.*;
import com.tmgsc.hifivetest.model.oa.filter.*;

@OAClass(useDataSource=false, localOnly=true)
@OAClassFilter(name = "Active", displayName = "Active", hasInputParams = false)
public class ProgramActiveFilter extends OAObject implements CustomHubFilter {
    private static final long serialVersionUID = 1L;


    public static final String PPCode = ":Active()";
    private Hub<Program> hubMaster;
    private Hub<Program> hub;
    private HubFilter<Program> filter;
    private boolean bAllHubs;

    public ProgramActiveFilter(Hub<Program> hub) {
        this(true, null, hub);
    }
    public ProgramActiveFilter(Hub<Program> hubMaster, Hub<Program> hub) {
        this(false, hubMaster, hub);
    }
    public ProgramActiveFilter(boolean bAllHubs, Hub<Program> hubMaster, Hub<Program> hubFiltered) {
        this.hubMaster = hubMaster;
        this.hub = hubFiltered;
        if (hubMaster == null) this.hubMaster = new Hub<Program>(Program.class);
        this.bAllHubs = bAllHubs;
        getHubFilter(); // create filter
    }


    public void reset() {
    }

    public boolean isDataEntered() {
        return false;
    }
    public void refresh() {
        if (filter != null) getHubFilter().refresh();
    }

    @Override
    public HubFilter<Program> getHubFilter() {
        if (filter == null) {
            filter = createHubFilter(hubMaster, hub, bAllHubs);
        }
        return filter;
    }
    protected HubFilter<Program> createHubFilter(final Hub<Program> hubMaster, Hub<Program> hub, boolean bAllHubs) {
        HubFilter<Program> filter = new HubFilter<Program>(hubMaster, hub) {
            @Override
            public boolean isUsed(Program program) {
                return ProgramActiveFilter.this.isUsed(program);
            }
        };
        filter.addDependentProperty(Program.P_InactiveDate);
        filter.addDependentProperty(Program.P_BeginDate);
        filter.addDependentProperty(Program.P_EndDate);
 
        if (!bAllHubs) return filter;
        final ArrayList<Hub> alHub = new ArrayList<Hub>();
        alHub.add(hub);
        alHub.add(hubMaster);
 
        OAObjectCacheDelegate.addListener(Program.class, new HubListenerAdapter() {
            @Override
            public void afterAdd(HubEvent e) {
                Hub h = e.getHub();
                if (h == null || alHub.contains(h)) return;
                alHub.add(h);
                Hub<Program> h2 = new Hub<Program>(Program.class);
                alHub.add(h2);
                createHubFilter(h, h2, false);
                h2.addHubListener(new HubListenerAdapter() {
                    @Override
                    public void afterAdd(HubEvent e) {
                        hubMaster.add((Program)e.getObject());
                    }
                    @Override
                    public void afterRemove(HubEvent e) {
                        Program obj = (Program) e.getObject();
                        if (!OAObjectHubDelegate.isInHub(obj)) {
                            hubMaster.remove(obj);
                        }
                    }
                });
            }
 
            @Override
            public void afterPropertyChange(HubEvent e) {
                String prop = e.getPropertyName();
                if (prop == null) return;
                if (prop.equalsIgnoreCase(Program.P_InactiveDate)) {
                    if (!hubMaster.contains(e.getObject())) hubMaster.add((Program) e.getObject());
                    return;
                }
                if (prop.equalsIgnoreCase(Program.P_BeginDate)) {
                    if (!hubMaster.contains(e.getObject())) hubMaster.add((Program) e.getObject());
                    return;
                }
                if (prop.equalsIgnoreCase(Program.P_EndDate)) {
                    if (!hubMaster.contains(e.getObject())) hubMaster.add((Program) e.getObject());
                    return;
                }
            }
        });
        return filter;
    }

    public boolean isUsed(Program program) {
        OADate now = new OADate();
        OADate d = program.getInactiveDate();
        if (d != null && d.compareTo(now) <= 0) return false;
        
        d = program.getBeginDate();
        if (d == null) return false;
        return true;
    }
    
}
