// Generated by OABuilder
package com.theicetest.tsactest.model.oa.propertypath;
 
import com.theicetest.tsactest.model.oa.*;
 
public class ServerTypeClientPP {
    private static ServerTypePPx serverType;
    private static ServerTypePPx toServerType;
     

    public static ServerTypePPx serverType() {
        if (serverType == null) serverType = new ServerTypePPx(ServerTypeClient.P_ServerType);
        return serverType;
    }

    public static ServerTypePPx toServerType() {
        if (toServerType == null) toServerType = new ServerTypePPx(ServerTypeClient.P_ToServerType);
        return toServerType;
    }

    public static String id() {
        String s = ServerTypeClient.P_Id;
        return s;
    }

    public static String verifiedInRepo() {
        String s = ServerTypeClient.P_VerifiedInRepo;
        return s;
    }
}
 
