// Generated by OABuilder
package com.tmgsc.hifivetest.model.oa.propertypath;
 
import com.tmgsc.hifivetest.model.oa.*;
 
public class CustomDataPP {
    private static EmployeeCustomDataPPx employeeCustomDatas;
    private static ProgramPPx program;
     

    public static EmployeeCustomDataPPx employeeCustomDatas() {
        if (employeeCustomDatas == null) employeeCustomDatas = new EmployeeCustomDataPPx(CustomData.P_EmployeeCustomDatas);
        return employeeCustomDatas;
    }

    public static ProgramPPx program() {
        if (program == null) program = new ProgramPPx(CustomData.P_Program);
        return program;
    }

    public static String id() {
        String s = CustomData.P_Id;
        return s;
    }

    public static String code() {
        String s = CustomData.P_Code;
        return s;
    }

    public static String name() {
        String s = CustomData.P_Name;
        return s;
    }

    public static String description() {
        String s = CustomData.P_Description;
        return s;
    }
}
 
