// Generated by OABuilder
package com.tmgsc.hifivetest.model.oa.propertypath;
 
import com.tmgsc.hifivetest.model.oa.*;
 
public class EcardCategoryPP {
    private static EcardPPx ecards;
     

    public static EcardPPx ecards() {
        if (ecards == null) ecards = new EcardPPx(EcardCategory.P_Ecards);
        return ecards;
    }

    public static String id() {
        String s = EcardCategory.P_Id;
        return s;
    }

    public static String name() {
        String s = EcardCategory.P_Name;
        return s;
    }

    public static String seq() {
        String s = EcardCategory.P_Seq;
        return s;
    }
}
 
