// Generated by OABuilder
package com.tmgsc.hifivetest.model.oa.propertypath;
 
import com.tmgsc.hifivetest.model.oa.*;
 
public class HifiveOrderCardPP {
    private static CardPPx card;
    private static HifiveOrderPPx hifiveOrder;
     

    public static CardPPx card() {
        if (card == null) card = new CardPPx(HifiveOrderCard.P_Card);
        return card;
    }

    public static HifiveOrderPPx hifiveOrder() {
        if (hifiveOrder == null) hifiveOrder = new HifiveOrderPPx(HifiveOrderCard.P_HifiveOrder);
        return hifiveOrder;
    }

    public static String id() {
        String s = HifiveOrderCard.P_Id;
        return s;
    }

    public static String created() {
        String s = HifiveOrderCard.P_Created;
        return s;
    }

    public static String seq() {
        String s = HifiveOrderCard.P_Seq;
        return s;
    }

    public static String pointsUsed() {
        String s = HifiveOrderCard.P_PointsUsed;
        return s;
    }

    public static String completedDate() {
        String s = HifiveOrderCard.P_CompletedDate;
        return s;
    }
}
 
