// Generated by OABuilder
package com.tmgsc.hifivetest.model.oa.propertypath;
 
import com.tmgsc.hifivetest.model.oa.*;
 
public class HifiveReasonPP {
    private static HifivePPx hifives;
    private static ProgramPPx program;
     

    public static HifivePPx hifives() {
        if (hifives == null) hifives = new HifivePPx(HifiveReason.P_Hifives);
        return hifives;
    }

    public static ProgramPPx program() {
        if (program == null) program = new ProgramPPx(HifiveReason.P_Program);
        return program;
    }

    public static String id() {
        String s = HifiveReason.P_Id;
        return s;
    }

    public static String name() {
        String s = HifiveReason.P_Name;
        return s;
    }

    public static String recommendedPoints() {
        String s = HifiveReason.P_RecommendedPoints;
        return s;
    }

    public static String description() {
        String s = HifiveReason.P_Description;
        return s;
    }
}
 
