// Generated by OABuilder
package com.tmgsc.hifivetest.model.oa.propertypath;
 
import com.tmgsc.hifivetest.model.oa.*;
 
public class InspireCoreValuePP {
    private static EmployeePPx employee;
    private static InspirePPx inspires;
    private static LocationPPx location;
    private static ProgramPPx program;
     

    public static EmployeePPx employee() {
        if (employee == null) employee = new EmployeePPx(InspireCoreValue.P_Employee);
        return employee;
    }

    public static InspirePPx inspires() {
        if (inspires == null) inspires = new InspirePPx(InspireCoreValue.P_Inspires);
        return inspires;
    }

    public static LocationPPx location() {
        if (location == null) location = new LocationPPx(InspireCoreValue.P_Location);
        return location;
    }

    public static ProgramPPx program() {
        if (program == null) program = new ProgramPPx(InspireCoreValue.P_Program);
        return program;
    }

    public static String id() {
        String s = InspireCoreValue.P_Id;
        return s;
    }

    public static String name() {
        String s = InspireCoreValue.P_Name;
        return s;
    }

    public static String seq() {
        String s = InspireCoreValue.P_Seq;
        return s;
    }
}
 
