// Generated by OABuilder
package com.tmgsc.hifivetest.model.oa.propertypath;
 
import com.tmgsc.hifivetest.model.oa.*;
 
public class ItemVendorPP {
    private static ItemPPx items;
     

    public static ItemPPx items() {
        if (items == null) items = new ItemPPx(ItemVendor.P_Items);
        return items;
    }

    public static String id() {
        String s = ItemVendor.P_Id;
        return s;
    }

    public static String created() {
        String s = ItemVendor.P_Created;
        return s;
    }

    public static String name() {
        String s = ItemVendor.P_Name;
        return s;
    }

    public static String notes() {
        String s = ItemVendor.P_Notes;
        return s;
    }
}
 
