// Generated by OABuilder
package com.tmgsc.hifivetest.model.oa.propertypath;
 
import com.tmgsc.hifivetest.model.oa.*;
 
public class LoginImagePP {
    private static ImageStorePPx imageStore;
    private static LoginImageSetPPx loginImageSet;
     

    public static ImageStorePPx imageStore() {
        if (imageStore == null) imageStore = new ImageStorePPx(LoginImage.P_ImageStore);
        return imageStore;
    }

    public static LoginImageSetPPx loginImageSet() {
        if (loginImageSet == null) loginImageSet = new LoginImageSetPPx(LoginImage.P_LoginImageSet);
        return loginImageSet;
    }

    public static String id() {
        String s = LoginImage.P_Id;
        return s;
    }

    public static String location() {
        String s = LoginImage.P_Location;
        return s;
    }

    public static String xPosition() {
        String s = LoginImage.P_XPosition;
        return s;
    }

    public static String yPosition() {
        String s = LoginImage.P_YPosition;
        return s;
    }
}
 
