// Generated by OABuilder
package com.tmgsc.hifivetest.model.oa.propertypath;
 
import com.tmgsc.hifivetest.model.oa.*;
 
public class LoginImageSetPP {
    private static LoginImagePPx loginImages;
    private static ProgramPPx programs;
     

    public static LoginImagePPx loginImages() {
        if (loginImages == null) loginImages = new LoginImagePPx(LoginImageSet.P_LoginImages);
        return loginImages;
    }

    public static ProgramPPx programs() {
        if (programs == null) programs = new ProgramPPx(LoginImageSet.P_Programs);
        return programs;
    }

    public static String id() {
        String s = LoginImageSet.P_Id;
        return s;
    }

    public static String created() {
        String s = LoginImageSet.P_Created;
        return s;
    }

    public static String name() {
        String s = LoginImageSet.P_Name;
        return s;
    }
}
 
