// Generated by OABuilder
package com.tmgsc.hifivetest.model.oa.propertypath;
 
import com.tmgsc.hifivetest.model.oa.*;
 
public class PagePP {
    private static PageInfoPPx pageInfos;
     

    public static PageInfoPPx pageInfos() {
        if (pageInfos == null) pageInfos = new PageInfoPPx(Page.P_PageInfos);
        return pageInfos;
    }

    public static String id() {
        String s = Page.P_Id;
        return s;
    }

    public static String created() {
        String s = Page.P_Created;
        return s;
    }

    public static String name() {
        String s = Page.P_Name;
        return s;
    }

    public static String description() {
        String s = Page.P_Description;
        return s;
    }

    public static String seq() {
        String s = Page.P_Seq;
        return s;
    }
}
 
