// Generated by OABuilder
package com.tmgsc.hifivetest.model.oa.propertypath;
 
import com.tmgsc.hifivetest.model.oa.*;
 
public class ProductAuditPP {
    private static ProductPPx product;
     

    public static ProductPPx product() {
        if (product == null) product = new ProductPPx(ProductAudit.P_Product);
        return product;
    }

    public static String id() {
        String s = ProductAudit.P_Id;
        return s;
    }

    public static String created() {
        String s = ProductAudit.P_Created;
        return s;
    }

    public static String cost() {
        String s = ProductAudit.P_Cost;
        return s;
    }

    public static String handlingCost() {
        String s = ProductAudit.P_HandlingCost;
        return s;
    }

    public static String note() {
        String s = ProductAudit.P_Note;
        return s;
    }
}
 
