// Generated by OABuilder
package com.tmgsc.hifivetest.model.oa.propertypath;
 
import com.tmgsc.hifivetest.model.oa.*;
 
public class ReportClassPP {
    private static ReportPPx reports;
     

    public static ReportPPx reports() {
        if (reports == null) reports = new ReportPPx(ReportClass.P_Reports);
        return reports;
    }

    public static String id() {
        String s = ReportClass.P_Id;
        return s;
    }

    public static String name() {
        String s = ReportClass.P_Name;
        return s;
    }

    public static String className() {
        String s = ReportClass.P_ClassName;
        return s;
    }
}
 
