// Generated by OABuilder
package com.tmgsc.hifivetest.model.oa.propertypath;
 
import com.tmgsc.hifivetest.model.oa.*;
 
public class WidgetPP {
    private static ProgramPPx programs;
     

    public static ProgramPPx programs() {
        if (programs == null) programs = new ProgramPPx(Widget.P_Programs);
        return programs;
    }

    public static String id() {
        String s = Widget.P_Id;
        return s;
    }

    public static String created() {
        String s = Widget.P_Created;
        return s;
    }

    public static String name() {
        String s = Widget.P_Name;
        return s;
    }

    public static String link() {
        String s = Widget.P_Link;
        return s;
    }
}
 
