// Generated by OABuilder
package com.theice.tsactest.model.oa.propertypath;
 
import com.theice.tsactest.model.oa.*;
 
public class RemoteClientPP {
    private static RemoteMessagePPx remoteMessages;
     

    public static RemoteMessagePPx remoteMessages() {
        if (remoteMessages == null) remoteMessages = new RemoteMessagePPx(RemoteClient.P_RemoteMessages);
        return remoteMessages;
    }

    public static String id() {
        String s = RemoteClient.P_Id;
        return s;
    }

    public static String name() {
        String s = RemoteClient.P_Name;
        return s;
    }

    public static String type() {
        String s = RemoteClient.P_Type;
        return s;
    }

    public static String started() {
        String s = RemoteClient.P_Started;
        return s;
    }

    public static String status() {
        String s = RemoteClient.P_Status;
        return s;
    }
}
 
