// Generated by OABuilder
package test.theice.tsam.remote;

import test.theice.tsam.model.oa.MRADServerCommand;
import com.viaoa.remote.multiplexer.annotation.OARemoteInterface;

import test.theice.tsam.delegate.*;
import test.theice.tsam.delegate.oa.*;
import test.theice.tsam.model.oa.*;
import test.theice.tsam.remote.RemoteMRADInterface;

@OARemoteInterface
public interface RemoteModelInterface {
    public final static String BindName = "RemoteModel";

    void mradServerCommand_runOnServer(MRADServerCommand mradServerCommand) throws Exception;
}

