// Generated by OABuilder
package test.theice.tsam.remote;

import test.theice.tsam.model.oa.MRADServerCommand;
import test.theice.tsam.remote.RemoteModelInterface;

import test.theice.tsam.delegate.*;
import test.theice.tsam.delegate.oa.*;
import test.theice.tsam.model.oa.*;
import test.theice.tsam.remote.RemoteMRADInterface;


public class RemoteModelImpl implements RemoteModelInterface {

    public void mradServerCommand_runOnServer(MRADServerCommand mradServerCommand) throws Exception {
        mradServerCommand.runOnServer();
    }
}

